"""add_collection_progress

Revision ID: 07d2bfb64dbf
Revises: c9550df5fe24
Create Date: 2026-05-15 13:42:22.464490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d2bfb64dbf'
down_revision: Union[str, Sequence[str], None] = 'c9550df5fe24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_run_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.String(length=200), nullable=False, comment='当前步骤描述'),
    sa.Column('progress_pct', sa.Integer(), nullable=False, comment='0-100 进度百分比'),
    sa.Column('estimated_remaining', sa.Integer(), nullable=False, comment='预计剩余秒数'),
    sa.Column('progress_type', sa.String(length=20), nullable=False, comment='progress / captcha / error / done'),
    sa.Column('detail', sa.Text(), nullable=True, comment='详细描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_progress')
    # ### end Alembic commands ###
