"""add_search_source_topic_collection_run

Revision ID: c9550df5fe24
Revises: 
Create Date: 2026-05-14 22:57:09.658994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9550df5fe24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False, comment='起始页面URL'),
    sa.Column('domain', sa.String(length=255), nullable=False, comment='自动从base_url提取域名'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='active/needs_intervention/disabled'),
    sa.Column('auth_status', sa.String(length=50), nullable=False, comment='none/logged_in/session_ok/session_expired/captcha_blocked'),
    sa.Column('auth_notes', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True, comment='JSON列表，如 \'["光子芯片","光计算"]\''),
    sa.Column('search_depth', sa.Integer(), nullable=False, comment='每次最多浏览页面数'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False, comment='daily/weekly/custom'),
    sa.Column('schedule_times', sa.Text(), nullable=True, comment='JSON时间数组如 \'["08:00","14:00","20:00"]\''),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=False),
    sa.Column('created_via', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('search_source_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='queued/in_progress/completed/partial/failed'),
    sa.Column('urls_scanned', sa.Integer(), nullable=False),
    sa.Column('urls_collected', sa.Integer(), nullable=False),
    sa.Column('sources_created', sa.Integer(), nullable=False),
    sa.Column('cards_created', sa.Integer(), nullable=False),
    sa.Column('error_info', sa.Text(), nullable=True, comment='JSON'),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['search_source_id'], ['search_sources.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_search_sources',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('search_source_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['search_source_id'], ['search_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'search_source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_search_sources')
    op.drop_table('collection_runs')
    op.drop_table('topics')
    op.drop_table('search_sources')
    # ### end Alembic commands ###
