"""add memory_synced to info_cards

Revision ID: e45a641704d6
Revises: 07d2bfb64dbf
Create Date: 2026-05-20 14:35:47.000004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45a641704d6'
down_revision: Union[str, Sequence[str], None] = '07d2bfb64dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_cards', sa.Column('memory_synced', sa.Boolean(), nullable=False, comment='是否已同步到记忆中'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_cards', 'memory_synced')
    # ### end Alembic commands ###
